# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qiitan < Formula
  desc "This is a sample app of github.com/Qiitadon/Qiitan-go. It simply prints 'Hello, Gopher!'."
  homepage "https://github.com/Qiitadon/Qiitan-go/"
  version "0.0.0-beta4"

  on_macos do
    url "https://github.com/Qiitadon/Qiitan-go/releases/download/v0.0.0-beta4/Qiitan-go_0.0.0-beta4_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "cfbb54722b3b1242ee52512802fd34b6404a8fe9df2d9298edc1b3af93429dd5"

    def install
      bin.install "qiitan"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qiitadon/Qiitan-go/releases/download/v0.0.0-beta4/Qiitan-go_0.0.0-beta4_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "70099030426ffc2836c64467a6d0dfcd1b69713bc123abf98e350c3ee9cebf92"

      def install
        bin.install "qiitan"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Qiitadon/Qiitan-go/releases/download/v0.0.0-beta4/Qiitan-go_0.0.0-beta4_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d4d7c7ed9a6b4628547dda7fe76c8b984f90c3d578ecefd2e6571e24277b2427"

      def install
        bin.install "qiitan"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Qiitadon/Qiitan-go/releases/download/v0.0.0-beta4/Qiitan-go_0.0.0-beta4_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "1b95dd48c0cd2396ed2c5bf89acf38b2e1715a0ea0fc036c6b64f9e84ac6068e"

      def install
        bin.install "qiitan"
      end
    end
  end

  test do
    system "#{bin}/qiitan --version"
  end
end
